[project]
name = "devops-maturity"
version = "0.1.0"
description = "A DevOps maturity assessment tool with CLI and Web interface."
authors = [
  { name = "Xianpeng Shen", email = "xianpeng.shen@gmail.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
keywords = [
  "devops",
  "maturity",
  "assessment",
  "cli",
  "web",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Framework :: FastAPI",
]

dependencies = [
  "fastapi",
  "pybadges",
  "typer",
  "jinja2",
  "pydantic"
]

[project.urls]
Homepage = "https://github.com/devops-maturity"
Repository = "https://github.com/devops-maturity/devops-maturity"
Issues = "https://github.com/devops-maturity/devops-maturity/issues"

[project.optional-dependencies]
dev = [
  "uvicorn[standard]",
  "pre-commit",
]

[project.scripts]
devops-maturity = "src.cli.main:app"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
