[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "devops-maturity"
version = "0.1.0"
description = "A DevOps maturity assessment tool with CLI and Web interface."
authors = [
  { name = "Xianpeng Shen", email = "xianpeng.shen@gmail.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Development Status :: alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

keywords = [
  "devops",
  "maturity",
  "assessment",
  "cli",
  "web",
]

dependencies = [
  "fastapi",
  "badgepy",
  "typer",
  "jinja2",
  "pydantic",
  "python-multipart",
  "sqlalchemy",
]

[project.optional-dependencies]
dev = [
  "ruff",
  "uvicorn",
]
test = [
  "fastapi",
  "httpx",
  "pytest",
  "pytest-cov",
]

[project.scripts]
devops-maturity = "src.cli.main:app"

[tool.mypy]
ignore_missing_imports = true
