[project]
name = "devops-maturity"
version = "0.1.0"
description = "A DevOps maturity assessment tool with CLI and Web interface."
authors = [
  { name = "Xianpeng Shen", email = "xianpeng.shen@gmail.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"



dependencies = [
  "fastapi",
  "badgepy",
  "typer",
  "jinja2",
  "pydantic",
]

[project.optional-dependencies]
dev = [
  "ruff",
  "uvicorn",
]
test = [
  "fastapi",
  "httpx",
  "pytest",
  "pytest-cov",
]

[project.scripts]
devops-maturity = "src.cli.main:app"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
