name: Release Drafter

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  # write permission is required to create a github release
  contents: write
  # write permission is required for autolabeler
  # otherwise, read permission is required at least
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into the default branch
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
